//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class webpages_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public webpages_Roles()
        {
            this.webpages_UsersInRoles = new HashSet<webpages_UsersInRoles>();
        }
            
        public int RoleId { get; set; }

        [Display(Name = "Role Name:")]

        [Required(ErrorMessage ="Role Name is Required.")]
        public string RoleName { get; set; }
        [Display(Name ="Role Code:")]
        [Required(ErrorMessage = "Role Code is Required.")]
        [Remote("CheckDuplicates", "Roles", HttpMethod = "POST", ErrorMessage = "Role Code already in use.")]
        public string RoleCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
    }
}
